version: '3'
services:
  main:
    build: .
    image: dina2505/cloudcomputing
    depends_on:
      - "mongodb"
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    ports:
      - "3030:3030"

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
