services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web_service
      - get_service
      - post_service
      - put_service
      - delete_service

  web_service:
    image: dina2505/homepage_service:latest
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    ports:
      - "8084:8084"
    depends_on:
      - mongodb

  get_service:
    image: dina2505/get_service:latest
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  post_service:
    image: dina2505/post_service:latest
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  put_service:
    image: dina2505/put_service:latest
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    ports:
      - "8082:8082"
    depends_on:
      - mongodb

  delete_service:
    image: dina2505/delete_service:latest
    environment:
      - DATABASE_URI=mongodb://mongodb:27017
    ports:
      - "8083:8083"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
